/// Infrastructure every app built from the template gets.
library;

export 'l10n/core_localizations.dart';
export 'src/bootstrap/app_shell.dart';
export 'src/bootstrap/bootstrap.dart';
export 'src/config/app_config.dart';
export 'src/config/flavor_check.dart';
export 'src/config/konteyner_platform.dart';
export 'src/logging/log_setup.dart';
export 'src/modules/konteyner_module.dart';
export 'src/network/api_call.dart';
export 'src/network/api_error_ui.dart';
export 'src/network/api_exception.dart';
export 'src/network/base_response.dart';
export 'src/network/dio_setup.dart';
export 'src/network/request_path.dart';
export 'src/permissions/no_permission_page.dart';
export 'src/permissions/permission_redirect.dart';
export 'src/permissions/permissions.dart';
export 'src/permissions/permissions_service.dart';
export 'src/preferences/preferences.dart';
export 'src/reporting/analytics.dart';
export 'src/reporting/error_reporter.dart';
export 'src/reporting/provider_failure_observer.dart';
export 'src/reporting/remote_flags.dart';
export 'src/reporting/report_dispatcher.dart';
export 'src/reporting/uncaught_errors.dart';
export 'src/router/fade_extension.dart';
export 'src/router/navigation_breadcrumb_observer.dart';
export 'src/router/slide_extension.dart';
export 'src/session/auth_interceptor.dart';
export 'src/session/session.dart';
export 'src/session/session_redirect.dart' hide splashWithFrom;
export 'src/storage/encrypted_box.dart';
export 'src/theme/konteyner_tokens.dart';
export 'src/update/app_version_source.dart';
export 'src/update/konteyner_upgrader_messages.dart';
export 'src/update/konteyner_upgrader_store.dart';
export 'src/update/update_gate.dart';
