include: ../analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - android/**
    - ios/**
    - web/**
    - macos/**
    - linux/**
    - windows/**
